// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfUGv9njph2F-k6wpAeA-oQwaHYDkuMS0',
    appId: '1:479565449513:web:8e72e4bad0e6c791360f38',
    messagingSenderId: '479565449513',
    projectId: 'week8-sample-lilyn27',
    authDomain: 'week8-sample-lilyn27.firebaseapp.com',
    storageBucket: 'week8-sample-lilyn27.firebasestorage.app',
    measurementId: 'G-FTHMYTX087',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN7t_7mfTt3yluFtI2wrH_LoIE0UPFU0M',
    appId: '1:479565449513:android:bc318b9792d70a6d360f38',
    messagingSenderId: '479565449513',
    projectId: 'week8-sample-lilyn27',
    storageBucket: 'week8-sample-lilyn27.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfUGv9njph2F-k6wpAeA-oQwaHYDkuMS0',
    appId: '1:479565449513:web:59ba649baa19c039360f38',
    messagingSenderId: '479565449513',
    projectId: 'week8-sample-lilyn27',
    authDomain: 'week8-sample-lilyn27.firebaseapp.com',
    storageBucket: 'week8-sample-lilyn27.firebasestorage.app',
    measurementId: 'G-LN1W4ZR7Q0',
  );
}
